name: Docker Image CI

on: [push, pull_request, workflow_dispatch]

jobs:
  perl:
    strategy:
      matrix:
        include:
          - version: "5.34"
            branches: "1.9,1.10,1.11,master"
          - version: "5.32"
            branches: "1.9,1.10,1.11"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Docker 'buildx'
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Repository
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check if pull request is merged into master
      id: check-merge
      run: |
        from_branch="${{ github.event.pull_request.head.ref }}"
        to_branch="${{ github.event.pull_request.base.ref }}"
        echo "{is_merge_into_master}={"$from_branch" != "$to_branch" && "$to_branch" == "master"}" >> $GITHUB_OUTPUT
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: ${{ steps.check-merge.outputs.is_merge_into_master == 'true' }}
        tags: ghcr.io/${{github.repository_owner}}/ledgersmb_circleci-perl:${{ matrix.version }}
        build-args: |
          perl=${{ matrix.version }}
          branches=${{ matrix.branches }}
        context: "{{defaultContext}}:perl"

  postgres:
    strategy:
      matrix:
        version: ['12', '13', '14']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Docker 'buildx'
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Repository
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check if pull request is merged into master
      id: check-merge
      run: |
        from_branch="${{ github.event.pull_request.head.ref }}"
        to_branch="${{ github.event.pull_request.base.ref }}"
        echo "{is_merge_into_master}={"$from_branch" != "$to_branch" && "$to_branch" == "master"}" >> $GITHUB_OUTPUT
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: ${{ steps.check-merge.outputs.is_merge_into_master == 'true' }}
        tags: ghcr.io/${{github.repository_owner}}/ledgersmb_circleci-postgres:${{ matrix.version }}
        build-args: |
          version=${{ matrix.version }}
        context: "{{defaultContext}}:postgres"
