name: Docker Image CI

on: [push, pull_request, workflow_dispatch]

jobs:
  perl:
    strategy:
      matrix:
        include:
          - version: "5.34"
            branches: "1.9,1.10,1.11,master"
          - version: "5.32"
            branches: "1.9,1.10,1.11"
          #- version: "5.30"
          #  branches: "1.9,1.10"
          #- version: "5.28"
          #  branches: "1.9"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@next
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        image_name: ${{github.repository_owner}}/ledgersmb_circleci-perl
        image_tag: ${{ matrix.version }}
        build_extra_args: "--build-arg perl=${{ matrix.version }} --build-arg branches=${{ matrix.branches }}"
        context: perl
        registry: ghcr.io
        pull_image_and_stages: false
        push_image_and_stages: true

  postgres:
    strategy:
      matrix:
        version: ['12', '13', '14']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@next
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        image_name: ${{github.repository_owner}}/ledgersmb_circleci-postgres
        image_tag: ${{ matrix.version }}
        build_extra_args: "--build-arg version=${{ matrix.version }}"
        context: postgres
        registry: ghcr.io
        pull_image_and_stages: false
        push_image_and_stages: true
