name: Docker Image CI

on: [push, pull_request, workflow_dispatch]

jobs:
  perl:
    strategy:
      matrix:
        include:
          - version: "5.34"
            branches: "1.9,1.10,1.11,master"
          - version: "5.36"
            branches: "1.9,1.10,1.11"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Docker 'buildx'
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Repository
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        tags: ghcr.io/${{github.repository_owner}}/ledgersmb_circleci-perl:${{ matrix.version }}
        build-args: |
          perl=${{ matrix.version }}
          branches=${{ matrix.branches }}
        context: "{{defaultContext}}:perl"

  postgres:
    strategy:
      matrix:
        version: ['12', '13', '14']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Docker 'buildx'
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Repository
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        tags: ghcr.io/${{github.repository_owner}}/ledgersmb_circleci-postgres:${{ matrix.version }}
        build-args: |
          version=${{ matrix.version }}
        context: "{{defaultContext}}:postgres"
