name: Docker Image CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

#TODO: Figure out caching. See https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows

jobs:
  primary:
    #if: ${{ github.ref }} == "primary"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_name: ${{ github.repository_owner }}/ledgersmb_circleci-primary
        image_tag: latest
        context: primary
        push_git_tag: true
  browsers:
    strategy:
      matrix:
        browser: ['chrome', 'firefox', 'phantomjs']
    needs: primary
    #if: ${{ github.ref == matrix.browser }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_name: ${{ github.repository_owner }}/ledgersmb_circleci-${{ matrix.browser }}
        image_tag: latest
        push_git_tag: true
        context: ${{ matrix.browser }}
  perl:
    strategy:
      matrix:
        version: ['5.24', '5.26', '5.28', '5.30']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_name: ${{ github.repository_owner }}/ledgersmb_circleci-perl
        image_tag: ${{ matrix.version }}
        build_extra_args: "--build-arg perl=${{ matrix.version }}"
        push_git_tag: true
        context: perl
        stages_image_name: "${{ github.repository_owner }}/ledgersmb_circleci-perl-${{ matrix.version }}-stages"
  postgres:
    strategy:
      matrix:
        version: ['9.5', '9.6', '10', '11', '12']
    needs: primary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_name: ${{ github.repository_owner }}/ledgersmb_circleci-postgres
        image_tag: ${{ matrix.version }}
        build_extra_args: "--build-arg postgres=${{ matrix.version }}"
        push_git_tag: true
        context: postgres
        stages_image_name: "${{ github.repository_owner }}/ledgersmb_circleci-postgres-${{ matrix.version }}-stages"
