name: Docker Image CI

on: [push, pull_request, workflow_dispatch]

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_name: ${{ github.repository_owner }}dev/ledgersmb_circleci-primary
        image_tag: latest
        context: primary
        push_git_tag: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
        push_image_and_stages: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
  browsers:
    strategy:
      matrix:
        browser: ['chrome', 'firefox', 'phantomjs']
    needs: primary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_name: ${{ github.repository_owner }}dev/ledgersmb_circleci-browsers
        image_tag: ${{ matrix.browser }}
        push_git_tag: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
        context: ${{ matrix.browser }}
        stages_image_name: "${{ github.repository_owner }}dev/ledgersmb_circleci-browsers-${{ matrix.browser }}-stages"
        push_image_and_stages: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
  perl:
    strategy:
      matrix:
        version: ['5.32', '5.34']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_name: ${{ github.repository_owner }}dev/ledgersmb_circleci-perl
        image_tag: ${{ matrix.version }}
        build_extra_args: "--build-arg perl=${{ matrix.version }}"
        push_git_tag: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
        context: perl
        stages_image_name: "${{ github.repository_owner }}dev/ledgersmb_circleci-perl-${{ matrix.version }}-stages"
        push_image_and_stages: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
  postgres:
    strategy:
      matrix:
        version: ['9.5', '9.6', '10', '11', '12']
    needs: primary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        image_name: ${{ github.repository_owner }}dev/ledgersmb_circleci-postgres
        image_tag: ${{ matrix.version }}
        build_extra_args: "--build-arg postgres=${{ matrix.version }}"
        push_git_tag: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
        context: postgres
        stages_image_name: "${{ github.repository_owner }}dev/ledgersmb_circleci-postgres-${{ matrix.version }}-stages"
        push_image_and_stages: ${{ github.event_name == 'push' || github.event.pull_request.merged }}
